// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD51w79IjV6W5hTBh37DXlEeTwAWPaurg4',
    appId: '1:508654410511:web:a3c967a24561556ce5bc7a',
    messagingSenderId: '508654410511',
    projectId: 'nuntius-b9cca',
    authDomain: 'nuntius-b9cca.firebaseapp.com',
    databaseURL: 'https://nuntius-b9cca-default-rtdb.firebaseio.com',
    storageBucket: 'nuntius-b9cca.appspot.com',
    measurementId: 'G-2F63Z23YL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEDyvOOGq38bx2E2Hg63Fs50qpTBlaFDk',
    appId: '1:508654410511:android:785fd84aadc2b0a5e5bc7a',
    messagingSenderId: '508654410511',
    projectId: 'nuntius-b9cca',
    databaseURL: 'https://nuntius-b9cca-default-rtdb.firebaseio.com',
    storageBucket: 'nuntius-b9cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmSIyHZnhglMLfVwIDL7vdRdg9uVy08Q',
    appId: '1:508654410511:ios:9b087acf40df91cfe5bc7a',
    messagingSenderId: '508654410511',
    projectId: 'nuntius-b9cca',
    databaseURL: 'https://nuntius-b9cca-default-rtdb.firebaseio.com',
    storageBucket: 'nuntius-b9cca.appspot.com',
    iosBundleId: 'com.khaterCS.nuntius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSmSIyHZnhglMLfVwIDL7vdRdg9uVy08Q',
    appId: '1:508654410511:ios:66105198d77b47d0e5bc7a',
    messagingSenderId: '508654410511',
    projectId: 'nuntius-b9cca',
    databaseURL: 'https://nuntius-b9cca-default-rtdb.firebaseio.com',
    storageBucket: 'nuntius-b9cca.appspot.com',
    iosBundleId: 'com.khaterCS.nuntius.RunnerTests',
  );
}
